spring.application.name=hirfa

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5400/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/app-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/app-realm/protocol/openid-connect/certs


#chargily pay v2 configuration
chargily.pay.api-key=test_sk_mhSyFFYf1MCVCktwbRYbjCCgNGYT44tE4jtKpoZO
chargily.pay.webhook-secret=test_sk_mhSyFFYf1MCVCktwbRYbjCCgNGYT44tE4jtKpoZO
chargily.pay.base-url=https://pay.chargily.net/test/api/v2
chargily.pay.success-url=http://localhost:3000/payment/success
chargily.pay.failure-url=http://localhost:3000/payment/failure